# Generated by Django 3.2.9 on 2021-11-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211117_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='descrcao',
            new_name='descricao',
        ),
    ]
